# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-19
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : hic-server/x86/docker-compose.yml
# Version    : 0.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************

version: '2'

services:
  db:
    image: mysql:latest
    volumes:
      - db-data-vol:/var/lib/mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Rft5-667g-3drTR-44DFv
      - MYSQL_DATABASE=hic
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=asfRA-456RfGH-TrY67GhjF

  db-setup:
    image: bkjeholt/mysql-setup:1.1.1-x86
    restart: 'no'
    links: 
      - db:mysql
    depends_on:
      - db

  hic-manager:
    image: bkjeholt/mqtt-manager:latest-x86
    restart: always
    links:
      - db:mysql
      - mqtt:mqtt
    depends_on:
      - db
      - db-setup
      - mqtt

volumes:
  db-data-vol: {}
