# ************************************************************************
# Product    : Home information and control
# Date       : 2017-02-20
# Copyright  : Copyright (C) 2016-2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mysql/docker-compose.yml
# Version    : 1.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************

version: '2.1'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db

  phpmyadmin:
    image: bkjeholt/phpmyadmin:latest-x86
    depends_on:
      - mysql
    restart: always
    links: 
      - mysql:db
    ports: 
      - "${PMA_PORT_NO}:80"

  manager:
    image: bkjeholt/mqtt-manager:dev-x86
    depends_on:
      - mysql
    restart: always
    links:
      - mysql:mysql
    environment:
      MYSQL_IP_ADDR: mysql
      MYSQL_PORT_NO: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: db
      MQTT_IP_ADDR: ${MQTT_IP_ADDR}
      MQTT_PORT_NO: ${MQTT_PORT_NO}
      DOCKER_CONTAINER_NAME: hic-manager
      DEBUG: ${DEBUG}

  ftp-backup:
    image: bkjeholt/mysql-backup-ftp:latest-x86
    depends_on:
      - mysql
    restart: always
    links:
      - mysql:mysql
    environment:
      FTP_HOST_ADDR: ${FTP_HOST}
      FTP_USER_NAME: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
      FTP_BACKUP_BASE_DIR: ${FTP_BACKUP_BASE_DIR}
      MYSQL_BACKUP_INTERVALL: ${FTP_BACKUP_INTERVALL}
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
      MYSQL_ENV_MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ENV_MYSQL_DATABASE: db
      
volumes:
  mysql_data: 
