# ************************************************************************
# Product    : Home information and control
# Date       : 2017-01-19
# Copyright  : Copyright (C) 2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : hic-server/docker-compose.yml-x86
# Version    : 0.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************

version: '2'

services:
  db:
    image: hypriot/rpi-mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Rft5-667g-3drTR-44DFv
      - MYSQL_DATABASE=hic
      - MYSQL_USER=hic_user
      - MYSQL_PASSWORD=asfRA-456RfGH-TrY67GhjF

  db-bu:
    image: bkjeholt/mysql-backup:2.0.3
    restart: always
    links:
      - db:mysql
    depends_on:
      - db
      - db-setup
    environment:
      - DROPBOX_API_KEY="QkanZHtSteMAAAAAAAAAGptkhlvELB4qXt5qHD_Xe8yEdz2ViFSGRGo0799MbBh4"
      - DROPBOX_PATH="Backups/mysql/backup"
      - MYSQL_BACKUP_INTERVALL="12"

  db-setup:
    image: bkjeholt/mysql-setup:latest
    restart: 'no'
    links: 
      - db:mysql
    depends_on:
      - db

  mqtt:
    image: openenergy/rpi-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"

  hic_manager:
    image: bkjeholt/mqtt-manager:latest
    restart: always
    links:
      - db:mysql
      - mqtt:mqtt
    depends_on:
      - db
      - db-setup
      - mqtt

volumes:
  mysql_data: 
